.'C:\Users\Paul\Desktop\Powershell Scripts\Functions\CreateSpellHotkeys.ps1'

CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button1' -ButtonName 'Fire 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '/pet qattack' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Mage2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'
CreateSpellHotkeys -SpellSlotCastingOrder '1,1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button2' -ButtonName 'Fire 2' -FirstRowText '/pause 4, /assist group' -SecondRowText '/pet qattack' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Mage2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'
CreateSpellHotkeys -SpellSlotCastingOrder '1,1,1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button3' -ButtonName 'Fire 3' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Mage2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'
<#--------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button4' -ButtonName 'Magic 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '/pet qattack' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Mage2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'
CreateSpellHotkeys -SpellSlotCastingOrder '2,2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button5' -ButtonName 'Magic 2' -FirstRowText '/pause 4, /assist group' -SecondRowText '/pet qattack' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Mage2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'
CreateSpellHotkeys -SpellSlotCastingOrder '2,2,2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button6' -ButtonName 'Magic 3' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Mage2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'
<#--------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button7' -ButtonName 'Just Pet' -FirstRowText '/pause 4, /assist group' -SecondRowText '/pet qattack' -ThirdRowText '' -FourthRowText '' -LastRowText '' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'
CreateSpellHotkeys -SpellSlotCastingOrder '6' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button8' -ButtonName 'Mala' -FirstRowText '/pause 4, /assist group' -SecondRowText '/pet qattack' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Mage2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'criticamassua'

CreateSpellHotkeys -SpellSlotCastingOrder '6,7' -SpellLoadoutName 'SummonStuff' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button12' -ButtonName 'Food' -FirstRowText '' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Mage4 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Criticamassua' 
CreateSpellHotkeys -SpellSlotCastingOrder '4,4,8,8' -SpellLoadoutName 'SummonStuff' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button6' -ButtonName 'Weapons' -FirstRowText '' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Mage4 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Criticamassua' 

CreateSpellHotkeys -SpellSlotCastingOrder '4' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button9' -ButtonName 'DS Tank' -FirstRowText '/pause 4, /target Sanctificus' -SecondRowText '/cast 4' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Mage4 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Criticamassua' 

