.'C:\Users\Paul\Desktop\Powershell Scripts\Functions\CreateSpellHotkeys.ps1'

CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button1' -ButtonName 'Fast T' -FirstRowText '/pause 4, /target sanctif' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'
CreateSpellHotkeys -SpellSlotCastingOrder '1,1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button2' -ButtonName 'Fast B' -FirstRowText '/pause 4, /target Sanav' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'
CreateSpellHotkeys -SpellSlotCastingOrder '1,1,1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button3' -ButtonName 'Fast C' -FirstRowText '/pause 4, /target mentalin' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'

<#--------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '7' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button4' -ButtonName 'Magic 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'
CreateSpellHotkeys -SpellSlotCastingOrder '7,7' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button5' -ButtonName 'Magic 2' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'
CreateSpellHotkeys -SpellSlotCastingOrder '7,7,7' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button6' -ButtonName 'Magic 3' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'
<#--------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button7' -ButtonName 'Hot T' -FirstRowText '/pause 4, /target sanctif' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'
CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button8' -ButtonName 'Hot B' -FirstRowText '/pause 4, /target Sanav' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'
CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button9' -ButtonName 'Hot C' -FirstRowText '/pause 4, /target mentalin' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater'


CreateSpellHotkeys -SpellSlotCastingOrder '4,5,6' -SpellLoadoutName 'default' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button6' -ButtonName 'Buff T' -FirstRowText '/pause 4, /target sanct' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric 2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 
CreateSpellHotkeys -SpellSlotCastingOrder '4,5,6' -SpellLoadoutName 'default' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button11' -ButtonName 'Buff B' -FirstRowText '/pause 4, /target Sana' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric 2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 
CreateSpellHotkeys -SpellSlotCastingOrder '4,5,6' -SpellLoadoutName 'default' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button12' -ButtonName 'Buff C' -FirstRowText '/pause 4, /target mental' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric 2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 
CreateSpellHotkeys -SpellSlotCastingOrder '4,5,6' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button1' -ButtonName 'Buff C' -FirstRowText '/pause 4, /target divina' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric 2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 
CreateSpellHotkeys -SpellSlotCastingOrder '4,5,6' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button2' -ButtonName 'Buff M' -FirstRowText '/pause 4, /target crit' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric 2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 
CreateSpellHotkeys -SpellSlotCastingOrder '4,5,6' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button3' -ButtonName 'Buff W' -FirstRowText '/pause 4, /target nuclear' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Cleric 2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button7' -ButtonName 'SpellH C' -FirstRowText '/pause 4, /target divinater' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button8' -ButtonName 'SpellH C' -FirstRowText '/pause 4, /target mentalint' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button9' -ButtonName 'SpellH M' -FirstRowText '/pause 4, /target criticamass' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button10' -ButtonName 'SpellH W' -FirstRowText '/pause 4, /target nuclearcrep' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Cleric2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button10' -ButtonName 'Light T' -FirstRowText '/pause 4, /target sanct' -SecondRowText '/gs Large Heal on %T' -ThirdRowText '/cast 5' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button11' -ButtonName 'Light B' -FirstRowText '/pause 4, /target Sanav' -SecondRowText '/gs Large Heal on %T' -ThirdRowText '/cast 5' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button12' -ButtonName 'Light C' -FirstRowText '/pause 4, /target Mentalin' -SecondRowText '/gs Large Heal on %T' -ThirdRowText '/cast 5' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button1' -ButtonName 'Fast C' -FirstRowText '/pause 4, /target Divin' -SecondRowText '/gs Fast Heal on %T' -ThirdRowText '/cast 1' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button2' -ButtonName 'Fast M' -FirstRowText '/pause 4, /target Criticam' -SecondRowText '/gs Fast Heal on %T' -ThirdRowText '/cast 1' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button3' -ButtonName 'Fast W' -FirstRowText '/pause 4, /target Nuclearm' -SecondRowText '/gs Fast Heal on %T' -ThirdRowText '/cast 1' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button4' -ButtonName 'Hot C' -FirstRowText '/pause 4, /target Divinater' -SecondRowText '/gs HOT on %T' -ThirdRowText '/cast 2' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button5' -ButtonName 'Hot M' -FirstRowText '/pause 4, /target Criticama' -SecondRowText '/gs HOT on %T' -ThirdRowText '/cast 2' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button6' -ButtonName 'Hot W' -FirstRowText '/pause 4, /target Nuclearc' -SecondRowText '/gs HOT on %T' -ThirdRowText '/cast 2' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button7' -ButtonName 'Light C' -FirstRowText '/pause 4, /target Divinater' -SecondRowText '/gs Large Heal on %T' -ThirdRowText '/cast 5' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button8' -ButtonName 'Light M' -FirstRowText '/pause 4, /target Criticam' -SecondRowText '/gs Large Heal on %T' -ThirdRowText '/cast 5' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

CreateSpellHotkeys -SpellSlotCastingOrder '5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button9' -ButtonName 'Light W' -FirstRowText '/pause 4, /target Nuclearc' -SecondRowText '/gs Large Heal on %T' -ThirdRowText '/cast 5' -FourthRowText '' -LastRowText '/sit' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Divinater' 

