.'C:\Users\Paul\Desktop\Powershell Scripts\Functions\CreateSpellHotkeys.ps1'

CreateSpellHotkeys -SpellSlotCastingOrder '8,3' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button1' -ButtonName 'Assist' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '3' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button2' -ButtonName 'Slow' -FirstRowText '' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '8,3' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button3' -ButtonName 'TS' -FirstRowText '' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
<#------------------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '7' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button4' -ButtonName 'Magic 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '7,7' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button5' -ButtonName 'Magic 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '7,7,7' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button6' -ButtonName 'Magic 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
<#------------------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button7' -ButtonName 'Mez 1' -FirstRowText '/pause 4, /xtar 2' -SecondRowText '' -ThirdRowText '/pause 11, /xtar 3' -FourthRowText '/cast 1' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button8' -ButtonName 'Mez 2' -FirstRowText '/pause 4, /xtar 4' -SecondRowText '' -ThirdRowText '/pause 11, /xtar 5' -FourthRowText '/cast 1' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button9' -ButtonName 'Mez 3' -FirstRowText '/pause 4, /xtar 6' -SecondRowText '' -ThirdRowText '/pause 11, /xtar 7' -FourthRowText '/cast 1' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button10' -ButtonName 'Mez 4' -FirstRowText '/pause 4, /xtar 8' -SecondRowText '' -ThirdRowText '/pause 11, /xtar 9' -FourthRowText '/cast 1' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button11' -ButtonName 'Mez 5' -FirstRowText '/pause 4, /xtar 10' -SecondRowText '' -ThirdRowText '/pause 11, /xtar 11' -FourthRowText '/cast 1' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button12' -ButtonName 'Mez 6' -FirstRowText '/pause 4, /xtar 12' -SecondRowText '' -ThirdRowText '/pause 11, /xtar 13' -FourthRowText '/cast 1' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
<#------------------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button7' -ButtonName 'Tash 1' -FirstRowText '/pause 4, /xtar 2' -SecondRowText '' -ThirdRowText '/pause 15, /xtar 3' -FourthRowText '/cast 8' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button8' -ButtonName 'Tash 2' -FirstRowText '/pause 4, /xtar 4' -SecondRowText '' -ThirdRowText '/pause 15, /xtar 5' -FourthRowText '/cast 8' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button9' -ButtonName 'Tash 3' -FirstRowText '/pause 4, /xtar 6' -SecondRowText '' -ThirdRowText '/pause 15, /xtar 7' -FourthRowText '/cast 8' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button10' -ButtonName 'Tash 4' -FirstRowText '/pause 4, /xtar 8' -SecondRowText '' -ThirdRowText '/pause 15, /xtar 9' -FourthRowText '/cast 8' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button11' -ButtonName 'Tash 5' -FirstRowText '/pause 4, /xtar 10' -SecondRowText '' -ThirdRowText '/pause 15, /xtar 11' -FourthRowText '/cast 8' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'
CreateSpellHotkeys -SpellSlotCastingOrder '8' -SpellLoadoutName 'default' -TargetHotkeyPage 'page5' -TargetHotkeyButton 'button12' -ButtonName 'Tash 6' -FirstRowText '/pause 4, /xtar 12' -SecondRowText '' -ThirdRowText '/pause 15, /xtar 13' -FourthRowText '/cast 8' -LastRowText '/gs Enchanter Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus'

CreateSpellHotkeys -SpellSlotCastingOrder '5,5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button6' -ButtonName 'C1' -FirstRowText '/pause 4, /target sanct' -SecondRowText '' -ThirdRowText '/pause 4, /target mental' -FourthRowText '' -LastRowText '/gs Enchanter2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus' 

CreateSpellHotkeys -SpellSlotCastingOrder '5,5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button11' -ButtonName 'C2' -FirstRowText '/pause 4, /target divinat' -SecondRowText '' -ThirdRowText '/pause 4, /target critica' -FourthRowText '' -LastRowText '/gs Enchanter2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus' 

CreateSpellHotkeys -SpellSlotCastingOrder '5' -SpellLoadoutName 'default' -TargetHotkeyPage 'page3' -TargetHotkeyButton 'button12' -ButtonName 'C3' -FirstRowText '/pause 4, /target nuclearcrep' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Enchanter2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus' 

CreateSpellHotkeys -SpellSlotCastingOrder '4,4' -SpellLoadoutName 'default' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button1' -ButtonName 'Haste' -FirstRowText '/pause 4, /target sanct' -SecondRowText '' -ThirdRowText '/pause 4, /target sanav' -FourthRowText '' -LastRowText '/gs Enchanter2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus' 
CreateSpellHotkeys -SpellSlotCastingOrder '5,5,5,5' -SpellLoadoutName 'ManaDrain' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button2' -ButtonName 'Mana Drain' -FirstRowText '' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Enchanter2 Script Done!' -CastTimeFocus '1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus' 

CreateSpellHotkeys -SpellSlotCastingOrder '' -SpellLoadoutName 'ManaDrain' -TargetHotkeyPage 'page7' -TargetHotkeyButton 'button3' -ButtonName 'Mem Mana' -FirstRowText '/mem ManaDrain' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '' -CastTimeFocus '1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'Mentalinteritus' 

