.'C:\Users\Paul\Desktop\Powershell Scripts\Functions\CreateSpellHotkeys.ps1'

CreateSpellHotkeys -SpellSlotCastingOrder '1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button1' -ButtonName 'Fire 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
CreateSpellHotkeys -SpellSlotCastingOrder '1,1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button2' -ButtonName 'Fire 2' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
CreateSpellHotkeys -SpellSlotCastingOrder '1,1,1' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button3' -ButtonName 'Fire 3' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
<#--------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button4' -ButtonName 'Magic 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
CreateSpellHotkeys -SpellSlotCastingOrder '2,2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button5' -ButtonName 'Magic 2' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
CreateSpellHotkeys -SpellSlotCastingOrder '2,2,2' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button6' -ButtonName 'Magic 3' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
<#--------------------#>
CreateSpellHotkeys -SpellSlotCastingOrder '3' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button7' -ButtonName 'Ice 1' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
CreateSpellHotkeys -SpellSlotCastingOrder '3,3' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button8' -ButtonName 'Ice 2' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '/sit' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
CreateSpellHotkeys -SpellSlotCastingOrder '3,3,3' -SpellLoadoutName 'default' -TargetHotkeyPage 'page4' -TargetHotkeyButton 'button9' -ButtonName 'Ice 3' -FirstRowText '/pause 4, /assist group' -SecondRowText '' -ThirdRowText '' -FourthRowText '' -LastRowText '/gs Wizard2 Script Done!' -CastTimeFocus '.1'  -EQDirectory 'C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\' -ServerName 'test' -CharacterName 'nuclearcrepitus' 
